# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/hydra-lightning
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Lightning
from dataclasses import dataclass
from dataclasses import field
from typing import Any
from typing import Callable
from typing import Optional

from omegaconf import MISSING


@dataclass
class AccuracyConf:
    _target_: str = "pytorch_lightning.metrics.classification.Accuracy"
    threshold: float = 0.5
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None
    dist_sync_fn: Callable = None


@dataclass
class FbetaConf:
    _target_: str = "pytorch_lightning.metrics.classification.Fbeta"
    num_classes: int = MISSING
    beta: float = 1.0
    threshold: float = 0.5
    average: str = "micro"
    multilabel: bool = False
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None


@dataclass
class PrecisionConf:
    _target_: str = "pytorch_lightning.metrics.classification.Precision"
    num_classes: int = 1
    threshold: float = 0.5
    average: str = "micro"
    multilabel: bool = False
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None
