# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/hydra-lightning 
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Lightning:

from dataclasses import dataclass, field
from omegaconf import MISSING


@dataclass
class MetricConf:
    _target_: str = "pytorch_lightning.metrics.Metric"
    name: str = MISSING
