# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/hydra-lightning
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Lightning

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any
from typing import Dict
from typing import Optional


@dataclass
class CometLoggerConf:
    _target_: str = "pytorch_lightning.loggers.CometLogger"
    api_key: Optional[str] = None
    save_dir: Optional[str] = None
    project_name: Optional[str] = None
    rest_api_key: Optional[str] = None
    experiment_name: Optional[str] = None
    experiment_key: Optional[str] = None
    offline: bool = False
    prefix: str = ""
    kwargs: Any = MISSING


@dataclass
class MLFlowLoggerConf:
    _target_: str = "pytorch_lightning.loggers.MLFlowLogger"
    experiment_name: str = "default"
    tracking_uri: Optional[str] = None
    tags: Optional[Dict[str, Any]] = None
    save_dir: Optional[str] = "./mlruns"
    prefix: str = ""


@dataclass
class NeptuneLoggerConf:
    _target_: str = "pytorch_lightning.loggers.NeptuneLogger"
    api_key: Optional[str] = None
    project_name: Optional[str] = None
    close_after_fit: Optional[bool] = True
    offline_mode: bool = False
    experiment_name: Optional[str] = None
    experiment_id: Optional[str] = None
    prefix: str = ""
    kwargs: Any = MISSING


@dataclass
class TestTubeLoggerConf:
    _target_: str = "pytorch_lightning.loggers.TestTubeLogger"
    save_dir: str = MISSING
    name: str = "default"
    description: Optional[str] = None
    debug: bool = False
    version: Optional[int] = None
    create_git_tag: bool = False
    log_graph: bool = False
    prefix: str = ""


@dataclass
class WandbLoggerConf:
    _target_: str = "pytorch_lightning.loggers.WandbLogger"
    name: Optional[str] = None
    save_dir: Optional[str] = None
    offline: bool = False
    id: Optional[str] = None
    anonymous: bool = False
    version: Optional[str] = None
    project: Optional[str] = None
    log_model: bool = False
    experiment: Any = None
    prefix: str = ""
    kwargs: Any = MISSING
