# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/hydra-lightning 
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Lightning:

from dataclasses import dataclass, field
from typing import Optional
import pytorch_lightning as pl
from packaging import version
import importlib

def override_imports_for_legacy():
    if version.parse(pl.__version__) < version.parse("1.0.0"):
        module = importlib.import_module('hydra_configs.pytorch_lightning_v090.metrics.regression')
        globals().update(
            {n: getattr(module, n) for n in module.__all__} if hasattr(module, '__all__') else 
            {k: v for (k, v) in module.__dict__.items() if not k.startswith('_')}
        )


@dataclass
class ExplainedVarianceConf:
    _target_: str = "pytorch_lightning.metrics.regression.ExplainedVariance"
    multioutput: str = "uniform_average"
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None


@dataclass
class MeanAbsoluteErrorConf:
    _target_: str = "pytorch_lightning.metrics.regression.MeanAbsoluteError"
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None


@dataclass
class MeanSquaredErrorConf:
    _target_: str = "pytorch_lightning.metrics.regression.MeanSquaredError"
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None


@dataclass
class MeanSquaredLogErrorConf:
    _target_: str = "pytorch_lightning.metrics.regression.MeanSquaredLogError"
    compute_on_step: bool = True
    dist_sync_on_step: bool = False
    process_group: Any = None
